### PR TITLE
Only use version we know work as dependency

### LINKED ISSUE #19: Your generator is broken
You're breaking your generator by defining your dependency version this way: https://github.com/notorii/generator-mean-seed/blob/master/package.json#L43-L47

The last release of yeoman-generator is not backward compatible and is breaking your generator.

### PR DESCRIPTION
**Pull request by SBoudrias**
Fix #19

For people having this issue in the meantime, you can install from my git fork directly: `npm -g install SBoudrias/generator-mean-seed#patch-1`

### CODE REVIEW

**Comment by awaemmanuel** [comment]
Hello sir, can you please approve or provide a fix for this issue? I'm using your generator and this is a showstopper.

**Comment by SBoudrias** [comment]
@awaemmanuel Just to make sure, you can install from my git fork directly: `npm -g install SBoudrias/generator-mean-seed#patch-1`

**Comment by SBoudrias** [comment]
Also, any chance pinging @lukemadera directly helps? I can see he's been active the last few days on Github.

**Comment by lukemadera** [comment]
@SBoudrias just merged. Sorry, been swamped!

**Pull request merged**
